# Generated by Django 3.0.4 on 2020-03-29 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200329_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 17, 6, 38, 151155, tzinfo=utc), null=True),
        ),
    ]
