# Generated by Django 3.0.4 on 2020-04-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200402_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='played',
        ),
    ]
