# Generated by Django 3.0.4 on 2020-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='flash',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='numbers',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
